<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datatypes"
    nsURI="http://www.mycompany.com/xmlns/prod/commerce" nsPrefix="_cust">
  <eClassifiers xsi:type="ecore:EClass" name="CustomCatalogRoot" eSuperTypes="../../Java-Annotation-Test/ecore/datatypes.ecore#//CatalogExampleRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CustomTestCatEntry" upperBound="-1"
        eType="#//CustomTestCatEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TestCatEntryCatEntryRelationship"
        upperBound="-1" eType="#//TestCatEntryCatEntryRelationship" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TestCatEntryDescription"
        upperBound="-1" eType="#//TestCatEntryDescription" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TestCatEntryProperty" upperBound="-1"
        eType="#//TestCatEntryProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomTestCatEntry" eSuperTypes="../../Java-Annotation-Test/ecore/datatypes.ecore#//TestCatEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCatEntryCatEntryRelationship"
        upperBound="-1" eType="#//TestCatEntryCatEntryRelationship" resolveProxies="false"
        eOpposite="#//TestCatEntryCatEntryRelationship/customTestCatEntryParent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCatEntryCatEntryRelationship2"
        upperBound="-1" eType="#//TestCatEntryCatEntryRelationship" resolveProxies="false"
        eOpposite="#//TestCatEntryCatEntryRelationship/customTestCatEntryChild"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCatEntryDescription"
        upperBound="-1" eType="#//TestCatEntryDescription" resolveProxies="false"
        eOpposite="#//TestCatEntryDescription/customTestCatEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testCatEntryProperty" upperBound="-1"
        eType="#//TestCatEntryProperty" resolveProxies="false" eOpposite="#//TestCatEntryProperty/customTestCatEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCatEntryCatEntryRelationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="catEntryCatEntryRelationshipId"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="childCatEntryId" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentCatEntryId" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customTestCatEntryChild"
        eType="#//CustomTestCatEntry" resolveProxies="false" eOpposite="#//CustomTestCatEntry/testCatEntryCatEntryRelationship2"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customTestCatEntryParent"
        eType="#//CustomTestCatEntry" resolveProxies="false" eOpposite="#//CustomTestCatEntry/testCatEntryCatEntryRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usageCode" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCatEntryDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="catEntryDescriptionId"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="catEntryId" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortDescription" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customTestCatEntry" eType="#//CustomTestCatEntry"
        resolveProxies="false" eOpposite="#//CustomTestCatEntry/testCatEntryDescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCatEntryProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="catEntryId" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="catEntryPropertyId" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customTestCatEntry" eType="#//CustomTestCatEntry"
        resolveProxies="false" eOpposite="#//CustomTestCatEntry/testCatEntryProperty"/>
  </eClassifiers>
</ecore:EPackage>
